name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Fix dependencies
        run: |
          sed -i '/ton_client/d' pubspec.yaml
          sed -i '/dartdoc/d' pubspec.yaml
          sed -i '/bloc_test/d' pubspec.yaml
          sed -i 's/intl: \^0.18.1/intl: ^0.19.0/' pubspec.yaml
          flutter pub get
      
      - name: Build APK
        run: flutter build apk --release
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
